# Global settings applied to the whole site.
#
# “publish” is the directory to publish (relative to root of your repo),
# “command” is your build command,

[build]
  publish = "dev/dist"
  command = "yarn build:dev"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.branch-site]
  publish = "docs/.vuepress/dist"
  command = "yarn build:docs"
